import{a as L,S as w,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const S="54242679-4f176982105516e8b81b54235",q="https://pixabay.com/api/",v=async(e,r=1)=>(await L.get(q,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data,d=document.querySelector(".gallery"),u=document.querySelector(".loader"),s=document.querySelector(".load-more"),E=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(){u&&u.classList.remove("hidden")}function H(){u&&u.classList.add("hidden")}function O(){s==null||s.classList.remove("hidden")}function f(){s==null||s.classList.add("hidden")}function P(){d&&(d.innerHTML="")}function x(e){if(!d)return;const r=e.map(({webformatURL:n,largeImageURL:c,tags:t,likes:o,views:a,comments:g,downloads:b})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${c}">
        <img class="gallery-image" src="${n}" alt="${t}" width="360"/>
        <div class="info">
          <p><b>Likes</b><br>${o}</p>
          <p><b>Views</b><br>${a}</p>
          <p><b>Comments</b><br>${g}</p>
          <p><b>Downloads</b><br>${b}</p>
        </div>
      </a>
    </li>
  `).join("");d.insertAdjacentHTML("beforeend",r),E.refresh()}const m=document.querySelector(".form"),A=document.querySelector(".load-more");let h="",i=1;m.addEventListener("submit",async e=>{e.preventDefault();const r=e.currentTarget.elements["search-text"].value.trim();if(!r){l.warning({message:"Please enter a search query"});return}h=r,i=1,P(),f(),await p(),m.reset()});A.addEventListener("click",async()=>{i+=1,f(),y(),await p()});async function p(){y();try{const e=await v(h,i);if(e.totalHits===0){l.error({message:"Sorry, there are no images matching <br> your search query.",position:"topRight"});return}x(e.hits),i>1&&B(),i*15>=e.totalHits?(f(),e.totalHits>0&&l.info({message:"We're sorry, but you've reached the end of search results."})):O()}catch(e){l.error({message:"Error fetching images!"}),console.error(e)}finally{H()}}function B(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
